### ISSUE TITLE
When home on navBar is pressed twice, app crashes

### ISSUE THREAD

**Issue by lh1207** [lh1207/LocoQuest#30]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.locoquest.app, PID: 20319
    java.lang.IllegalStateException: Fragment already added: Home{703bf68} (f511cd7e-3e0a-42bd-8a0a-4d7012aa9d3e id=0x7f08007c tag=HomeFragment)
        at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:91)
        at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1713)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:415)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2404)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2162)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by derrickadkins** [comment]
I added "if(fragment.isAdded) return" just before the line that causes this
